build:
  stage: build
  image:
    name: docker
  services:
    - name: docker:dind
      command: ["--insecure-registry=$NEXUS_REGISTRY"]
  before_script:
    - echo "$NEXUS_PASSWORD" | docker login -u "$NEXUS_USER" --password-stdin "$NEXUS_REGISTRY" 
  script:
    - docker build -t $NEXUS_REGISTRY/besu-network .
    - docker push $NEXUS_REGISTRY/besu-network
  after_script:
    - docker logout $NEXUS_REGISTRY
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
