version: '3.7'

services:

   besu:
      build: .
      container_name: besu
      restart: unless-stopped
      env_file: .env.besu
      volumes: [ "/besu" ]
      ports:
        - "30303:30303/udp"
        - "30303:30303/tcp"
        - "8545:8545/tcp"
        - "8546:8546/tcp"      
      # docker-compose exec besu besu public-key export-address 
